name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      
      - name: Install dependencies
        run: npm ci

      - name: Check next version
        id: version
        run: echo ::set-output name=SEMANTIC_TAG::$(echo $(npx semantic-release --dryRun | grep -oP 'Published release \K.*? '))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Build image `
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: latest,${{ steps.version.outputs.SEMANTIC_TAG }}

    outputs:
      SEMANTIC_TAG: "${{ steps.version.outputs.SEMANTIC_TAG }}"